version: '3.8'

services:
  # Override app service for production
  app:
    build:
      target: production
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres123@postgres:5432/muse3dstudio
      - REDIS_URL=redis://redis:6379
      - NEXTAUTH_URL=${NEXTAUTH_URL:-https://muse3dstudio.com}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    volumes: []  # Remove volume mounts for production
    command: npm start
    restart: always

  # Production PostgreSQL optimizations
  postgres:
    environment:
      POSTGRES_SHARED_PRELOAD_LIBRARIES: pg_stat_statements
    command: >
      postgres
      -c max_connections=100
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
    restart: always

  # Production Redis optimizations
  redis:
    command: >
      redis-server
      --appendonly yes
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    restart: always

  # Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: muse3d_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - muse3d_network
    depends_on:
      - app
    restart: always

  # Remove tools services in production
  prisma-studio:
    profiles:
      - disabled

  pgadmin:
    profiles:
      - disabled 